name: Metrics
on:
  # Schedule weekly updates
  schedule: [{cron: "0 0 * * 0"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: dlevchuk
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Kyiv
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_repositories: yes
          plugin_repositories_pinned: 4
          plugins_errors_fatal: no

      - name: Generate coding habits
        uses: lowlighter/metrics@latest
        with:
          filename: github-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: dlevchuk
          template: classic
          base: ""
          config_timezone: Europe/Kyiv
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugins_errors_fatal: no
